export const siteConfig = {
name: "Bhuvanesh Perumal Samy",
title: "MSCS at USC | Agentic AI, Distributed Systems & ML Infrastructure",
description: "Portfolio website of Bhuvanesh Perumal Samy",
accentColor: "#1dbcd8ff",
social: {
email: "perumals@usc.edu",
linkedin: "https://www.linkedin.com/in/bhuvanesh-perumal-samy-3335a8184/",
github: "https://github.com/BhuvaneshP-87",
},
aboutMe:
"I am a software engineer and researcher focused on building scalable AI systems, distributed backend platforms and ML-driven infrastructure. Currently, I am pursuing my Master of Science in Computer Science at the University of Southern California and working as a Research Assistant at USC Marshall School of Business, where I am designing a distributed agentic RAG pipeline that processes 45K+ legal documents and develops evaluation frameworks for retrieval quality, reasoning accuracy and inference performance across large-scale legal analytics workflows.\n\nPreviously, I worked as a Software Development Engineer at AiDash, where I developed LLM-powered document generation workflows using LangGraph, enhanced geospatial computer vision pipelines with LoRA-based PEFT and built high-throughput distributed Java microservices processing 1M+ records. I also optimized large-scale SQL and Python data pipelines processing 50M+ records, reducing runtimes from hours to minutes.\n\nBefore that, at Juspay, I worked on fintech infrastructure including merchant onboarding automation, audit logging systems, payment reconciliation and Python-based transaction synchronization services on AWS. My work spans Agentic AI, RAG systems, LLM workflows, computer vision, distributed systems, cloud infrastructure and production-scale backend engineering. I am particularly interested in bridging AI research with reliable, scalable production systems.",
skills: [
"Python",
"Java",
"C++",
"JavaScript",
"SQL",
"PyTorch",
"TensorFlow",
"LangChain",
"LangGraph",
"LLMs",
"RAG Systems",
"AWS",
"Docker",
"Kubernetes",
"Kafka",
"Spark",
"CUDA",
"Distributed Systems",
],
skillCategories: [
{
name: "Languages",
items: ["Python", "Java", "JavaScript", "C++", "SQL"],
},
{
name: "Web Technologies",
items: [
"Django",
"Spring Boot",
"React.js",
"Node.js",
"Redux",
"Hibernate",
"Maven",
"RESTful APIs",
],
},
{
name: "AI / ML",
items: [
"PyTorch",
"TensorFlow",
"LLMs",
"RAG Systems",
"LangChain",
"LangGraph",
"Computer Vision",
"Object Detection",
"Image Classification",
"OpenCV",
"LoRA",
"PEFT",
"Vision Transformers",
"CNNs",
"Deep Learning",
],
},
{
name: "Cloud Services",
items: [
"AWS EC2",
"AWS VPC",
"AWS Lambda",
"AWS SageMaker",
"AWS SNS",
"AWS EBS",
"AWS SQS",
"Azure",
"GCP",
],
},
{
name: "Databases",
items: [
"MySQL",
"PostgreSQL",
"MongoDB",
"Firebase",
"Redis",
"GraphQL",
"DynamoDB",
],
},
{
name: "Developer Tools",
items: [
"Git",
"Jenkins",
"Terraform",
"Docker",
"Kubernetes",
"Kafka",
"Grafana",
"Kibana",
"Linux",
"Unix",
"Jira",
],
},
{
name: "Systems",
items: [
"Distributed Systems",
"CI/CD",
"Infrastructure as Code",
"Containers",
"Spark",
"CUDA",
],
},
],
projects: [
{
name: "Distributed Agentic RAG Pipeline for Legal Analytics",
description:
"Designed a distributed agentic RAG system processing 45K+ legal documents. Built retrieval evaluation frameworks, reasoning benchmarks, vector indexing pipelines and large-scale inference workflows to measure retrieval quality, reasoning accuracy and system performance across legal analytics tasks.",
link: "",
skills: [
"Python",
"LLMs",
"RAG",
"LangGraph",
"LangChain",
"Vector Databases",
"Distributed Systems",
"Evaluation Frameworks",
],
},
{
name: "GPU Workload Anomaly Detection for Large-Scale Compute Clusters",
description:
"Built a distributed GPU telemetry analytics pipeline using PyTorch, Spark, Kafka and Grafana to analyze utilization, latency and memory metrics, enabling large-scale experimentation, performance optimization and bottleneck detection across compute clusters.",
link: "",
skills: [
"Python",
"PyTorch",
"Spark",
"Kafka",
"CUDA Telemetry",
"Grafana",
],
},
{
name: "Cost-Aware Small–Large Model Routing for Unsupervised Anomaly Detection",
description:
"Developed a cost-aware computer vision framework using PyTorch, CNNs, Vision Transformers and object detection to identify anomalies in CCTV footage while dynamically routing inference between lightweight and high-capacity models to optimize latency and accuracy.",
link: "",
skills: [
"Python",
"TensorFlow",
"PyTorch",
"Distributed ML Pipeline",
"MAE",
"ViT",
"pandas",
"scikit-learn",
],
},
{
name: "Visual Memory Graph for Spatio-Temporal Video Analytics",
description:
"Built a visual memory graph system using OpenCV, YOLOv8, DeepSORT and Neo4j to maintain spatial and temporal relationships between objects, enabling real-time scene understanding and audio-guided navigation for visually impaired users.",
link: "",
skills: [
"PyTorch",
"OpenCV",
"YOLOv8",
"DeepSORT",
"Neo4j",
"LangChain",
],
},
{
name: "Song Recommendation System to Improve Mental State",
description:
"Engineered an AI-driven mental wellness platform leveraging NLP, reinforcement learning and speech-based deep learning models for emotion classification and personalized music recommendations, achieving 82% text and 80% audio classification accuracy.",
link: "https://www.irjmets.com/uploadedfiles/paper/issue_7_july_2022/27915/final/fin_irjmets1657529466.pdf",
skills: [
"React",
"Node.js",
"Python",
"TensorFlow",
"PyTorch",
"AWS",
"NLP",
"Reinforcement Learning",
],
},
],
experience: [
{
company: "USC Marshall School of Business",
title: "Research Assistant",
dateRange: "Jan 2026 - Present",
bullets: [
"Designed a distributed agentic RAG pipeline processing 45K+ legal documents, developing evaluation frameworks to benchmark retrieval quality, reasoning accuracy and inference performance across large-scale legal analytics workflows.",
],
},
{
company: "AiDash Inc",
title: "Software Development Engineer",
dateRange: "Jun 2024 - Aug 2025",
bullets: [
"Drove development of an LLM-powered topographical document generation platform using LangGraph, collaborating across teams to automate content generation and validation workflows, reducing processing time and saving $12K annually.",
"Led enhancements to a geospatial computer vision pipeline using LoRA-based PEFT, feature engineering, TensorBoard-driven experimentation and model evaluation, expanding coverage to 14 tree species classes and improving classification accuracy across large-scale satellite imagery datasets.",
"Owned end-to-end computer vision and deep learning pipelines, driving workflow automation, feature engineering, model training and experimental validation to improve data quality and enable scalable experimentation across geospatial datasets.",
"Led delivery of high-throughput distributed Java microservices processing 1M+ records, driving platform reliability, CI/CD automation and performance optimizations that reduced processing time from 10 hours to 5 minutes.",
"Optimized large-scale data pipelines processing 50M+ records using SQL and Python, refining query execution plans, memory management and batch processing through profiling and parallel execution, reducing runtime from 16 hours to 10 minutes.",
],
},
{
company: "Juspay Technologies Pvt Ltd",
title: "Software Development Engineer",
dateRange: "Mar 2022 - May 2024",
bullets: [
"Led the design and rollout of a merchant onboarding automation system, partnering with banking and engineering stakeholders to streamline workflows and reduce processing time from 10 days to under 5 minutes.",
"Led development of an activity tracking and audit logging platform processing 100K+ daily user actions, defining observability requirements and improving operational monitoring and debugging efficiency across production environments.",
"Engineered an automated payment reconciliation feature for 500+ merchants, slashing manual finance workflows by 90% and ensuring accurate daily payouts via scheduled batch processing.",
"Developed Python-based transaction synchronization services on AWS EC2, leveraging cron-driven automation, structured logging and error handling to improve system reliability and reduce manual operational effort by 95%.",
],
},
],
education: [
{
school: "University of Southern California",
degree: "Master of Science in Computer Science",
dateRange: "Aug 2025 - May 2027",
achievements: [
"Courses: Deep Learning, ML for Data Science, Database Systems, Agentic Artificial Intelligence",
],
},
{
school: "Dayananda Sagar College of Engineering",
degree: "Bachelor's in Computer Science",
dateRange: "Jul 2018 - Jul 2022",
achievements: [
"Courses: Data Structures and Algorithms, Computer Architecture, Operating Systems, Machine Learning",
],
},
],
};
